language: php
php:
 - 5.3
 - 5.4
 - 5.5
 - 5.6
 
branches:
  - master

matrix:
  include:
    - php: 5.6
      env: VARIA=true
      before_script:
       - cd ../../
       - node -v
       - pear install pear/PHP_CodeSniffer
       - phpenv rehash
       - git clone -b 1.9 https://github.com/Elgg/Elgg.git Elgg
       - mv hypeJunction/hypeFilestore Elgg/mod/hypeFilestore
       - cd Elgg/mod/hypeFilestore && composer update && cd ../../../
      script:
       - phpcs --standard=Elgg/mod/hypeFilestore/vendors/elgg/sniffs/elgg.xml --warning-severity=0 --ignore=*Elgg/mod/hypeFilestore/tests/*,*Elgg/mod/hypeFilestore/vendors/* Elgg/mod/hypeFilestore/
       - phpunit --configuration=Elgg/mod/hypeFilestore/phpunit.xml --coverage-clover=Elgg/mod/hypeFilestore/coverage.clover
       - composer validate --verbose Elgg/mod/hypeFilestore/composer.json
      after_script:
       - cd Elgg/mod/hypeFilestore
       - wget https://scrutinizer-ci.com/ocular.phar
       - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

services:
 - mysql

before_script:
 - cd ../../
 - git clone -b 1.9 https://github.com/Elgg/Elgg.git Elgg
 - mv hypeJunction/hypeFilestore Elgg/mod/hypeFilestore
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f Elgg/install/cli/travis_installer.php
 - php -f Elgg/mod/hypeFilestore/.travis/activate.php

script:
 - php -f Elgg/engine/tests/suite.php
 - phpunit --configuration=Elgg/mod/hypeFilestore/phpunit.xml

notifications:
  email: false